function theGame(){var d=0,e=1,f=3;function g(){this.a=[];for(var a=0;a<12;++a){this.a.push(a);this.a.push(a)}this.b=[]}function h(a,b){var c=a.c;if(!a.b[b]&&c!=b)if(c!=null){a.c=null;if(a.a[b]==a.a[c]){a.b[c]=true;a.b[b]=true;return d}else return e}else{a.c=b;return f}else return 2}function i(a){for(var b=0,c=0;c<24;++c)a.b[c]&&++b;return b/2}g.prototype.reset=function(){for(var a=this.a,b=a.length;b>1;--b){var c=Math.floor(Math.random()*b),l=a[c];a[c]=a[b-1];a[b-1]=l}for(a=0;a<24;++a)this.b[a]=false};var j=true;try{document.createEvent("TouchEvent")}catch(k){j=false}var m=null,n=0;
function o(a){a.preventDefault();var b="";switch(a.type){case "mousedown":b="touchstart";m=a.target;break;case "mousemove":if(!m)return;b="touchmove";break;case "mouseup":b="touchend";n++}if(m!=null){a={clientX:a.clientX,clientY:a.clientY,identifier:n,pageX:a.pageX,pageY:a.pageY,screenX:a.screenX,screenY:a.screenY,target:m};var c=document.createEvent("UIEvent");c.initEvent(b,true,false);c.type=b;c.touches=b=="touchend"?[]:[a];c.targetTouches=b=="touchend"?[]:[a];c.changedTouches=[a];m.dispatchEvent(c);
if(b=="touchend")m=null}};var p=0,q=document.getElementById("playTheGame");if(!j){document.addEventListener("mousemove",o,true);document.addEventListener("mouseup",o,true);document.addEventListener("mousedown",o,true)}var r=navigator.userAgent.indexOf("iPhone")>=0||navigator.userAgent.indexOf("iPad")>=0||navigator.userAgent.indexOf("iPod")>=0;if(r)q.className+=" has3D";q.innerHTML='<div id="stage"><div id="cube"></div></div><span id="score" class="hud"></span>';
var s=document.getElementById("stage"),t=document.getElementById("cube"),u,v,w=0,x=0,y,z=new g,A="";
if(r)for(var B=["Y(0","Y(90","Y(180","Y(270","X(90","X(-90"],C=0;C<6;++C){A+="<div class='side' style='-webkit-transform: rotate"+B[C]+"deg) translateZ(100px)'>";A+="<div style='position:absolute'>";for(var D=0;D<4;++D)A+="<div class='card front'></div>";A+="</div>";A+="<div style='pointer-events:none; position:absolute'>";for(D=0;D<4;++D)A+="<div class='card back'></div>";A+="</div>";A+="</div>"}else for(C=0;C<6;++C){A+="<div class='side'>";A+="<div style='position:absolute'>";for(D=0;D<4;++D)A+=
"<div class='card front'></div>";A+="</div>";A+="<div style='pointer-events:none; position:absolute'>";for(D=0;D<4;++D)A+="<div class='card back'></div>";A+="</div>";A+="</div>"}t.innerHTML=A;for(var E=t.querySelectorAll(".front"),F=t.querySelectorAll(".back"),G=0;G<E.length;++G)E[G].d=G;function H(a){a.style.webkitTransform=r?"translateZ(50px)":"scale(1.2,1.2)";a.style.opacity="0"}function I(a){a.style.webkitTransform=r?"translateZ(0)":"scale(1,1)";a.style.opacity="1"}
function J(){p=Date.now();z.reset();for(var a=0;a<E.length;++a){var b=z.a[a],c=E[a];c.className="card front";c.style.backgroundPosition=(r?100:60)*(b+1)+"px";I(F[a])}document.getElementById("score").innerText="0 / 12"}s.addEventListener("touchstart",function(a){a=a.touches[0];u=a.screenX;v=a.screenY;y=true},false);
r&&s.addEventListener("touchmove",function(a){var b=a.touches[0];a=u-b.screenX;b=v-b.screenY;t.style.webkitTransform="rotateY("+-(a+w)+"deg) rotateX("+(b+x)+"deg)";if(Math.abs(a)>10||Math.abs(b)>10)y=false},false);
function K(a){a=a.changedTouches[0];var b=v-a.screenY;w+=u-a.screenX;x+=b;if(y){var c=a.target.d;if(c!=null){var l=z.c;switch(h(z,c)){case e:H(F[c]);setTimeout(function(){I(F[l]);I(F[c])},500);break;case d:H(F[c]);E[l].className+=" found";E[c].className+=" found";document.getElementById("score").innerText=i(z)+" / 12";if(z.b.indexOf(false)==-1){alert("Nice! Your time score "+Math.max(0,1E3-Math.floor((Date.now()-p)/1E3))+".");J()}break;case f:H(F[c])}}}}s.addEventListener("touchend",K,false);
s.addEventListener("touchcancel",K,false);window.addEventListener("load",function(){setTimeout(function(){window.scrollTo(0,1)},100)},false);document.addEventListener("touchstart",function(a){a.preventDefault();window.scrollTo(0,1)},false);J();}